EVAL_PORTFOLIO_SPECS = {"value_weighted_monthly_k50_tc5":{"portfolio_size":50,
                                                "turnover_cost_bps": 5,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=5"},
                    "value_weighted_monthly_k50_tc15":{"portfolio_size":50,
                                                "turnover_cost_bps": 15,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=15"},
                    "value_weighted_monthly_k50_tc35": {"portfolio_size": 50,
                                                "turnover_cost_bps": 35,
                                                "rebalancing_frequency": "monthly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=35"},
                    "equally_weighted_monthly_k50_tc5":{"portfolio_size":50,
                                                "turnover_cost_bps": 5,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=5"},
                    "equally_weighted_monthly_k50_tc15":{"portfolio_size":50,
                                                "turnover_cost_bps": 15,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=15"},
                    "equally_weighted_monthly_k50_tc35": {"portfolio_size": 50,
                                                "turnover_cost_bps": 35,
                                                "rebalancing_frequency": "monthly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=35"},
                    "conjugate_hf_vix_vw_monthly_k50_tc5_ra5_h1_l1":{"portfolio_size": 50,
                                                  "turnover_cost_bps": 5,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                  "display_name": "Conjugate HF-VIX VW tc=5, ra=5"},
                    "conjugate_hf_vix_vw_monthly_k50_tc15_ra5_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 15,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                  "display_name": "Conjugate HF-VIX VW tc=15, ra=5"},
                    "conjugate_hf_vix_vw_monthly_k50_tc35_ra5_h1_l1": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 35,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "conjugate_hf_vix",
                                                 "prior_n": "vix_scaling",
                                                 "h_l": (1, 1),
                                                 "risk_aversion": 5,
                                                 "rolling_window_days": 1000,
                                                 "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                 "display_name": "Conjugate HF-VIX VW tc=35, ra=5"},
                    "conjugate_hf_vix_ew_monthly_k50_tc5_ra5_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 5,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("equally_weighted", "equally_weighted"),
                                                  "display_name": "Conjugate HF-VIX EW tc=5, ra=5"},
                    "conjugate_hf_vix_ew_monthly_k50_tc15_ra5_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 15,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("equally_weighted", "equally_weighted"),
                                                 "display_name": "Conjugate HF-VIX EW tc=15, ra=5"},
                    "conjugate_hf_vix_ew_monthly_k50_tc35_ra5_h1_l1": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 35,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "conjugate_hf_vix",
                                                 "prior_n": "vix_scaling",
                                                 "h_l": (1, 1),
                                                 "risk_aversion": 5,
                                                 "rolling_window_days": 1000,
                                                 "prior_weights_h_l": (
                                                 "equally_weighted", "equally_weighted"),
                                                 "display_name": "Conjugate HF-VIX EW tc=35, ra=5"},
                    "jeffreys_monthly_k50_tc5_ra5_h1_l1": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "jeffreys",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jeffreys tc=5, ra=5"},
                    "jeffreys_monthly_k50_tc15_ra5_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 15,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "jeffreys",
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Jeffreys tc=15, ra=5"},
                    "jeffreys_monthly_k50_tc35_ra5_h1_l1": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 35,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "jeffreys",
                                                 "risk_aversion": 5,
                                                 "rolling_window_days": 1000,
                                                 "display_name": "Jeffreys tc=35, ra=5"},
                    "shrinkage_monthly_k50_tc5_ra5": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 5,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "shrinkage",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Ledoit-Wolf Shrinkage tc=5, ra=5"},
                    "shrinkage_monthly_k50_tc15_ra5": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 15,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "shrinkage",
                                                 "covariance_matrix_estimation": "shrinkage",
                                                 "risk_aversion": 5,
                                                 "rolling_window_days": 1000,
                                                 "display_name": "Ledoit-Wolf Shrinkage tc=15, ra=5"},
                    "shrinkage_monthly_k50_tc35_ra5": {"portfolio_size": 50,
                                                "turnover_cost_bps": 35,
                                                "rebalancing_frequency": "monthly",
                                                "weights_spec": "shrinkage",
                                                "covariance_matrix_estimation": "shrinkage",
                                                "risk_aversion": 5,
                                                "rolling_window_days": 1000,
                                                "display_name": "Ledoit-Wolf Shrinkage tc=35, ra=5"},
                    "black_litterman_monthly_k50_tc5_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "black_litterman",
                                                   "covariance_matrix_estimation": "shrinkage",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Black-Litterman tc=5, ra=5"},
                    "black_litterman_monthly_k50_tc15_ra5": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 15,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "black_litterman",
                                                   "covariance_matrix_estimation": "shrinkage",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Black-Litterman tc=15, ra=5"},
                    "black_litterman_monthly_k50_tc35_ra5": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 35,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "black_litterman",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Black-Litterman tc=35, ra=5"},
                    "jorion_hyper_monthly_k50_tc5_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=5, ra=5"},
                    "jorion_hyper_monthly_k50_tc15_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 15,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=15, ra=5"},
                    "jorion_hyper_monthly_k50_tc35_ra5": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 35,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "jorion_hyper",
                                                   "covariance_matrix_estimation": "jorion_hyper",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jorion Hyperpar. tc=35, ra=5"},
                    "hierarchical_monthly_k50_tc5_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=5, ra=5"},
                    "hierarchical_monthly_k50_tc15_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 15,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=15, ra=5"},
                    "hierarchical_monthly_k50_tc35_ra5": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 35,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "hierarchical",
                                                  "covariance_matrix_estimation": "hierarchical",
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Greyserman Hiera. tc=35, ra=5"}
}