EVAL_PORTFOLIO_SPECS = {"value_weighted_weekly_k50_tc1":{"portfolio_size":50,
                                                "turnover_cost_bps": 1,
                                                "rebalancing_frequency":"weekly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=1"},
                    "value_weighted_weekly_k50_tc3":{"portfolio_size":50,
                                                "turnover_cost_bps": 3,
                                                "rebalancing_frequency":"weekly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=3"},
                    "equally_weighted_weekly_k50_tc1":{"portfolio_size":50,
                                                "turnover_cost_bps": 1,
                                                "rebalancing_frequency":"weekly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=1"},
                    "equally_weighted_weekly_k50_tc3":{"portfolio_size":50,
                                                "turnover_cost_bps": 3,
                                                "rebalancing_frequency":"weekly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=3"},
                     "conjugate_hf_vix_weekly_k50_tc1_ra5_h1_l1":{"portfolio_size": 50,
                                                  "turnover_cost_bps": 1,
                                                  "rebalancing_frequency": "weekly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                  "display_name": "Conjugate HF-VIX tc=1, ra=5"},
                    "conjugate_hf_vix_weekly_k50_tc3_ra5_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 3,
                                                  "rebalancing_frequency": "weekly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": (
                                                  "value_weighted", "value_weighted"),
                                                  "display_name": "Conjugate HF-VIX tc=3, ra=5"},
                    "conjugate_hf_vix_weekly_k50_tc1_ra10_h1_l1": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "conjugate_hf_vix",
                                                   "prior_n": "vix_scaling",
                                                   "h_l": (1, 1),
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                   "display_name": "Conjugate HF-VIX tc=1, ra=10"},
                    "conjugate_hf_vix_weekly_k50_tc3_ra10_h1_l1": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 3,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "conjugate_hf_vix",
                                                   "prior_n": "vix_scaling",
                                                   "h_l": (1, 1),
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "prior_weights_h_l": (
                                                   "value_weighted", "value_weighted"),
                                                   "display_name": "Conjugate HF-VIX tc=3, ra=10"},
                    "jeffreys_weekly_k50_tc1_ra5_h1_l1": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "jeffreys",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jeffreys tc=1, ra=5"},
                    "jeffreys_weekly_k50_tc3_ra5_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 3,
                                                  "rebalancing_frequency": "weekly",
                                                  "weights_spec": "jeffreys",
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Jeffreys tc=3, ra=5"},
                    "jeffreys_weekly_k50_tc1_ra10_h1_l1": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 1,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "jeffreys",
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jeffreys tc=1, ra=10"},
                    "jeffreys_weekly_k50_tc3_ra10_h1_l1": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 3,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "jeffreys",
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jeffreys tc=3, ra=10"},
                    "shrinkage_weekly_k50_tc1_ra5": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 1,
                                                  "rebalancing_frequency": "weekly",
                                                  "weights_spec": "shrinkage",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 5,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Ledoit-Wolf Shrinkage tc=1, ra=5"},
                    "shrinkage_weekly_k50_tc3_ra5": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 3,
                                                 "rebalancing_frequency": "weekly",
                                                 "weights_spec": "shrinkage",
                                                 "covariance_matrix_estimation": "shrinkage",
                                                 "risk_aversion": 5,
                                                 "rolling_window_days": 1000,
                                                 "display_name": "Ledoit-Wolf Shrinkage tc=3, ra=5"},
                    "shrinkage_weekly_k50_tc1_ra10": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 1,
                                                  "rebalancing_frequency": "weekly",
                                                  "weights_spec": "shrinkage",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 10,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Ledoit-Wolf Shrinkage tc=1, ra=10"},
                    "shrinkage_weekly_k50_tc3_ra10": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 3,
                                                  "rebalancing_frequency": "weekly",
                                                  "weights_spec": "shrinkage",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 10,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Ledoit-Wolf Shrinkage tc=3, ra=10"},
                    "black_litterman_weekly_k50_tc1_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "black_litterman",
                                                   "covariance_matrix_estimation": "shrinkage",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Black-Litterman tc=1, ra=5"},
                    "black_litterman_weekly_k50_tc3_ra5": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 3,
                                                   "rebalancing_frequency": "weekly",
                                                   "weights_spec": "black_litterman",
                                                   "covariance_matrix_estimation": "shrinkage",
                                                   "risk_aversion": 5,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Black-Litterman tc=3, ra=5"},
                    "black_litterman_weekly_k50_tc1_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "black_litterman",
                                                    "covariance_matrix_estimation": "shrinkage",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Black-Litterman tc=1, ra=10"},
                    "black_litterman_weekly_k50_tc3_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 3,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "black_litterman",
                                                    "covariance_matrix_estimation": "shrinkage",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Black-Litterman tc=3, ra=10"},
                    "jorion_hyper_weekly_k50_tc1_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=1, ra=5"},
                    "jorion_hyper_weekly_k50_tc3_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 3,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=3, ra=5"},
                    "jorion_hyper_weekly_k50_tc1_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=1, ra=10"},
                    "jorion_hyper_weekly_k50_tc3_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 3,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=3, ra=10"},
                    "hierarchical_weekly_k50_tc1_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=1, ra=5"},
                    "hierarchical_weekly_k50_tc3_ra5": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 3,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 5,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=3, ra=5"},
                    "hierarchical_weekly_k50_tc1_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 1,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=1, ra=10"},
                    "hierarchical_weekly_k50_tc3_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 3,
                                                    "rebalancing_frequency": "weekly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=3, ra=10"}
}