EVAL_PORTFOLIO_SPECS = {"value_weighted_monthly_k50_tc5":{"portfolio_size":50,
                                                "turnover_cost_bps": 5,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=5"},
                    "value_weighted_monthly_k50_tc15":{"portfolio_size":50,
                                                "turnover_cost_bps": 15,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=15"},
                    "value_weighted_monthly_k50_tc35": {"portfolio_size": 50,
                                                "turnover_cost_bps": 35,
                                                "rebalancing_frequency": "monthly",
                                                "weights_spec": "value_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Value Weighted tc=35"},
                    "equally_weighted_monthly_k50_tc5":{"portfolio_size":50,
                                                "turnover_cost_bps": 5,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=5"},
                    "equally_weighted_monthly_k50_tc15":{"portfolio_size":50,
                                                "turnover_cost_bps": 15,
                                                "rebalancing_frequency":"monthly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=15"},
                    "equally_weighted_monthly_k50_tc35": {"portfolio_size": 50,
                                                "turnover_cost_bps": 35,
                                                "rebalancing_frequency": "monthly",
                                                "weights_spec": "equally_weighted",
                                                "rolling_window_days": 1000,
                                                "display_name": "Equally Weighted tc=35"},
                    "conjugate_hf_vix_vw_monthly_k50_tc5_ra1.3_h1_l1":{"portfolio_size": 50,
                                                  "turnover_cost_bps": 5,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 1.3,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                  "display_name": "Conjugate HF-VIX VW tc=5, ra=1.3"},
                    "conjugate_hf_vix_vw_monthly_k50_tc15_ra1.3_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 15,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 1.3,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                  "display_name": "Conjugate HF-VIX VW tc=15, ra=1.3"},
                    "conjugate_hf_vix_vw_monthly_k50_tc35_ra1.3_h1_l1": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 35,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "conjugate_hf_vix",
                                                 "prior_n": "vix_scaling",
                                                 "h_l": (1, 1),
                                                 "risk_aversion": 1.3,
                                                 "rolling_window_days": 1000,
                                                 "prior_weights_h_l": ("value_weighted", "value_weighted"),
                                                 "display_name": "Conjugate HF-VIX VW tc=35, ra=1.3"},
                    "conjugate_hf_vix_ew_monthly_k50_tc5_ra1.3_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 5,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 1.3,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("equally_weighted", "equally_weighted"),
                                                  "display_name": "Conjugate HF-VIX EW tc=5, ra=1.3"},
                    "conjugate_hf_vix_ew_monthly_k50_tc15_ra1.3_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 15,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "conjugate_hf_vix",
                                                  "prior_n": "vix_scaling",
                                                  "h_l": (1, 1),
                                                  "risk_aversion": 1.3,
                                                  "rolling_window_days": 1000,
                                                  "prior_weights_h_l": ("equally_weighted", "equally_weighted"),
                                                 "display_name": "Conjugate HF-VIX EW tc=15, ra=1.3"},
                    "conjugate_hf_vix_ew_monthly_k50_tc35_ra1.3_h1_l1": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 35,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "conjugate_hf_vix",
                                                 "prior_n": "vix_scaling",
                                                 "h_l": (1, 1),
                                                 "risk_aversion": 1.3,
                                                 "rolling_window_days": 1000,
                                                 "prior_weights_h_l": (
                                                 "equally_weighted", "equally_weighted"),
                                                 "display_name": "Conjugate HF-VIX EW tc=35, ra=1.3"},
                    "jeffreys_monthly_k50_tc5_ra20_h1_l1": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "jeffreys",
                                                   "risk_aversion": 20,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jeffreys tc=5, ra=20"},
                    "jeffreys_monthly_k50_tc15_ra20_h1_l1": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 15,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "jeffreys",
                                                  "risk_aversion": 20,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Jeffreys tc=15, ra=20"},
                    "jeffreys_monthly_k50_tc35_ra20_h1_l1": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 35,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "jeffreys",
                                                 "risk_aversion": 20,
                                                 "rolling_window_days": 1000,
                                                 "display_name": "Jeffreys tc=35, ra=20"},
                    "shrinkage_monthly_k50_tc5_ra23": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 5,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "shrinkage",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 23,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Ledoit-Wolf Shrinkage tc=5, ra=23"},
                    "shrinkage_monthly_k50_tc15_ra23": {"portfolio_size": 50,
                                                 "turnover_cost_bps": 15,
                                                 "rebalancing_frequency": "monthly",
                                                 "weights_spec": "shrinkage",
                                                 "covariance_matrix_estimation": "shrinkage",
                                                 "risk_aversion": 23,
                                                 "rolling_window_days": 1000,
                                                 "display_name": "Ledoit-Wolf Shrinkage tc=15, ra=23"},
                    "shrinkage_monthly_k50_tc35_ra23": {"portfolio_size": 50,
                                                "turnover_cost_bps": 35,
                                                "rebalancing_frequency": "monthly",
                                                "weights_spec": "shrinkage",
                                                "covariance_matrix_estimation": "shrinkage",
                                                "risk_aversion": 23,
                                                "rolling_window_days": 1000,
                                                "display_name": "Ledoit-Wolf Shrinkage tc=35, ra=23"},
                    "black_litterman_monthly_k50_tc5_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "black_litterman",
                                                   "covariance_matrix_estimation": "shrinkage",
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Black-Litterman tc=5, ra=10"},
                    "black_litterman_monthly_k50_tc15_ra10": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 15,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "black_litterman",
                                                   "covariance_matrix_estimation": "shrinkage",
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Black-Litterman tc=15, ra=10"},
                    "black_litterman_monthly_k50_tc35_ra10": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 35,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "black_litterman",
                                                  "covariance_matrix_estimation": "shrinkage",
                                                  "risk_aversion": 10,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Black-Litterman tc=35, ra=10"},
                    "jorion_hyper_monthly_k50_tc5_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=5, ra=10"},
                    "jorion_hyper_monthly_k50_tc15_ra10": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 15,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "jorion_hyper",
                                                    "covariance_matrix_estimation": "jorion_hyper",
                                                    "risk_aversion": 10,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Jorion Hyperpar. tc=15, ra=10"},
                    "jorion_hyper_monthly_k50_tc35_ra10": {"portfolio_size": 50,
                                                   "turnover_cost_bps": 35,
                                                   "rebalancing_frequency": "monthly",
                                                   "weights_spec": "jorion_hyper",
                                                   "covariance_matrix_estimation": "jorion_hyper",
                                                   "risk_aversion": 10,
                                                   "rolling_window_days": 1000,
                                                   "display_name": "Jorion Hyperpar. tc=35, ra=10"},
                    "hierarchical_monthly_k50_tc5_ra3": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 5,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 3,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=5, ra=3"},
                    "hierarchical_monthly_k50_tc15_ra3": {"portfolio_size": 50,
                                                    "turnover_cost_bps": 15,
                                                    "rebalancing_frequency": "monthly",
                                                    "weights_spec": "hierarchical",
                                                    "covariance_matrix_estimation": "hierarchical",
                                                    "risk_aversion": 3,
                                                    "rolling_window_days": 1000,
                                                    "display_name": "Greyserman Hiera. tc=15, ra=3"},
                    "hierarchical_monthly_k50_tc35_ra3": {"portfolio_size": 50,
                                                  "turnover_cost_bps": 35,
                                                  "rebalancing_frequency": "monthly",
                                                  "weights_spec": "hierarchical",
                                                  "covariance_matrix_estimation": "hierarchical",
                                                  "risk_aversion": 3,
                                                  "rolling_window_days": 1000,
                                                  "display_name": "Greyserman Hiera. tc=35, ra=3"}
}